### ISSUE TITLE
Bad link in the readme

### ISSUE THREAD

**Issue by jungletek** [PacktPublishing/Mastering-Game-Development-with-Unreal-Engine-4-Second-Edition#1]
The line: ```We also provide a PDF file that has color images of the screenshots/diagrams used in this book. [https://www.packtpub.com/sites/default/files/downloads/9781788991445_ColorImages.pdf](Graphics Bundle Link).``` has the brackets and parentheses flipped, so that the link is parsed incorrectly, and can't be directly clicked on.

**Comment by MurtazaTinwala** [comment]
Hi @jungletek 

Thanks for the update. Its rectified now.

Regards
