### ISSUE TITLE
It doesnt Compile with UE4.20 and VSC 2015

### ISSUE THREAD

**Issue by rezadarooei** [PacktPublishing/Mastering-Game-Development-with-Unreal-Engine-4-Second-Edition#2]
Hi, I didn't why it doesn't open in Ue4.20 and vscode 2015?

**Comment by githubce** [comment]
The book was written on UE 4.19. To open it in UE 4.20, you should convert the project to UE 4.20 version and if there are C++ codes in your project, you will have to rebuild the binaries.
