### ISSUE TITLE
Suggest: Do you consider the epub version?

### ISSUE THREAD

**Issue by JohnHe404** [PacktPublishing/Mastering-Game-Development-with-Unreal-Engine-4-Second-Edition#3]
My English is very poor and I need to use translation to read, but my ipad reader only supports epub and pdf. The reading experience of pdf is very poor. In addition, most books have epub format?

**Comment by ralph14** [comment]
Hi @HeMinzhang 

Could you please let me know which PDF reader you are using to read our books?

**Comment by JohnHe404** [comment]
https://wiki.mobileread.com/wiki/Duokan Duokan reader

**Comment by JohnHe404** [comment]
I have obtained the epub format for this book.Thx everyone.
