### ISSUE TITLE
'AController::Possess': function declared as 'final' cannot be overridden by 'AMeleeAIController::Possess'

### ISSUE THREAD

**Issue by ashishbairwa** [PacktPublishing/Mastering-Game-Development-with-Unreal-Engine-4-Second-Edition#4]
I'm facing an issue while generating the code. Log informations are as shown:

C:\"Program Files"\EpicGames\UE_4.22\Engine\Binaries\DotNET\UnrealBuildTool.exe -projectfiles -project="C:\Users\Barny\Documents\Desktop\Mastering\Mastering.uproject" -game -engine -progress -2015The project could not be compiled. Would you like to open it in Visual Studio?

Running C:/Program Files/EpicGames/UE_4.22/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Win64 -Project="G:/Mastering-Game-Development-with-Unreal-Engine-4-Second-Edition-master/Mastering.uproject" -TargetType=Editor -Progress -NoHotReloadFromIDE
Creating makefile for MasteringEditor (no existing makefile)
@progress push 5%
Parsing headers for MasteringEditor
  Running UnrealHeaderTool "G:\Mastering-Game-Development-with-Unreal-Engine-4-Second-Edition-master\Mastering.uproject" "G:\Mastering-Game-Development-with-Unreal-Engine-4-Second-Edition-master\Intermediate\Build\Win64\MasteringEditor\Development\MasteringEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
Reflection code generated for MasteringEditor in 25.6000787 seconds
@progress pop
Using Visual Studio 2017 14.16.27023 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023) and Windows 10.0.17763.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Building 38 actions with 4 processes...
  @progress 'Compiling C++ source code...' 0%
  @progress 'Compiling C++ source code...' 3%
  [1/38] Default.rc2
  @progress 'Compiling C++ source code...' 5%
  [2/38] SharedPCH.Engine.cpp
  @progress 'Compiling C++ source code...' 8%
  [3/38] MasteringWeaponPickup.cpp
  @progress 'Compiling C++ source code...' 11%
  [4/38] MasteringWeapon.cpp
  @progress 'Compiling C++ source code...' 13%
  [5/38] MasteringInventory.cpp
  @progress 'Compiling C++ source code...' 16%
  [6/38] MasteringIconCamera.cpp
  @progress 'Compiling C++ source code...' 18%
  [7/38] MeleeAIController.cpp
  g:\mastering-game-development-with-unreal-engine-4-second-edition-master\source\mastering\ai\MeleeAIController.h(24): error C3248: 'AController::Possess': function declared as 'final' cannot be overridden by 'AMeleeAIController::Possess'
  C:\Program Files\EpicGames\UE_4.22\Engine\Source\Runtime\Engine\Classes\GameFramework/Controller.h(266): note: see declaration of 'AController::Possess'
  G:\Mastering-Game-Development-with-Unreal-Engine-4-Second-Edition-master\Source\Mastering\AI\MeleeAIController.cpp(88): warning C4458: declaration of 'Owner' hides class member
  C:\Program Files\EpicGames\UE_4.22\Engine\Source\Runtime\Engine\Classes\GameFramework/Actor.h(431): note: see declaration of 'AActor::Owner'
  @progress 'Compiling C++ source code...' 21%
  [8/38] LoadSaveLibrary.cpp
  @progress 'Compiling C++ source code...' 24%
  [9/38] Mastering.cpp
  @progress 'Compiling C++ source code...' 26%
  [10/38] MasteringInventoryDisplay.cpp
  @progress 'Compiling C++ source code...' 29%
  [11/38] MasteringGameInstance.cpp
  @progress 'Compiling C++ source code...' 32%
  [12/38] MainMenuWidget.cpp
  @progress 'Compiling C++ source code...' 34%
  [13/38] SavedActorInterface.cpp
  @progress 'Compiling C++ source code...' 37%
  [14/38] MasteringGameMode.cpp
  @progress 'Compiling C++ source code...' 39%
  [15/38] MasteringCharacter.cpp
  @progress 'Compiling C++ source code...' 42%
  [16/38] LevelTransitionVolume.gen.cpp
  @progress 'Compiling C++ source code...' 45%
  [17/38] LevelTransitionVolume.cpp
  @progress 'Compiling C++ source code...' 47%
  [18/38] Mastering.init.gen.cpp
  @progress 'Compiling C++ source code...' 50%
  [19/38] MasteringCharacter.gen.cpp
  @progress 'Compiling C++ source code...' 53%
  [20/38] MasteringGameInstance.gen.cpp
  @progress 'Compiling C++ source code...' 55%
  [21/38] MasteringGameMode.gen.cpp
  @progress 'Compiling C++ source code...' 58%
  [22/38] MasteringHUD.gen.cpp
  @progress 'Compiling C++ source code...' 61%
  [23/38] MasteringIconCamera.gen.cpp
  @progress 'Compiling C++ source code...' 63%
  [24/38] StealthCharacter.cpp
  @progress 'Compiling C++ source code...' 66%
  [25/38] MasteringInventory.gen.cpp
  @progress 'Compiling C++ source code...' 68%
  [26/38] MainMenuWidget.gen.cpp
  @progress 'Compiling C++ source code...' 71%
  [27/38] MasteringHUD.cpp
  @progress 'Compiling C++ source code...' 74%
  [28/38] MasteringProjectile.gen.cpp
  @progress 'Compiling C++ source code...' 76%
  [29/38] MasteringWeapon.gen.cpp
  @progress 'Compiling C++ source code...' 79%
  [30/38] MasteringWeaponPickup.gen.cpp
  @progress 'Compiling C++ source code...' 82%
  [31/38] SavedActorInterface.gen.cpp
  @progress 'Compiling C++ source code...' 84%
  [32/38] StealthCharacter.gen.cpp
  @progress 'Compiling C++ source code...' 87%
  [33/38] MeleeAIController.gen.cpp
  G:\Mastering-Game-Development-with-Unreal-Engine-4-Second-Edition-master\Source\Mastering/AI/MeleeAIController.h(24): error C3248: 'AController::Possess': function declared as 'final' cannot be overridden by 'AMeleeAIController::Possess'
  C:\Program Files\EpicGames\UE_4.22\Engine\Source\Runtime\Engine\Classes\GameFramework/Controller.h(266): note: see declaration of 'AController::Possess'
  @progress 'Compiling C++ source code...' 89%
  [34/38] MasteringProjectile.cpp
  @progress 'Compiling C++ source code...' 92%
  [35/38] MasteringInventoryDisplay.gen.cpp

**Comment by ashishbairwa** [comment]
Done!  It's pretty simple. Unreal Engine deprecated the Possess and made it final. Using OnPossess will resolve this issue. :)

**Comment by mattedmonds404** [comment]
Hi, sorry for the late reply: yes, in 4.22 and onwards, "Possess" was
changed by Epic to be "OnPossess": this is fixed in one place on GitHub,
but I did not go back to all the branches to make that change.  Hopefully
this is an easy fix for you to make locally :)

-Matt
