### ISSUE TITLE
Chapter 1 - one important instruction is missing

### ISSUE THREAD

**Issue by marcinsztajn** [PacktPublishing/Mastering-Game-Development-with-Unreal-Engine-4-Second-Edition#5]
Hi,
I am usnig Polish version of a book and during first chapter I noticed that my program wasn't working. After few hours of searching the issue I found out that you forgot to mention that after creating new C++ class named Stealth you need to connect is somehow with FirstPersonCharacter Blueprint. So I would suggest to add an information about changing class settings in FirstPersonCharacter Blueprint from Parent Class Mastering to Stealth. I am new to UE4 and I found it very difficult to solve it.
Regards

**Comment by daivscott** [comment]
Thanks for this help marcinsztajn. To clarify a little for others, open the **FirstPersonCharacter Blueprint** in full editor mode and click the **Class Settings** button, now in the Details Panel on the right change the **Parent Class** option to **Stealth Character**( click the drop-down, then just begin type Stealth in the search box of the drop-down to help find it) then save and play :)

**Comment by X-Carolinii-X** [comment]
I also use the Polish version of the book and have a different problem with the first chapter. Namely, if I change the parent class to Stealth, I cannot control the camera left and right with the mouse after clicking the play button and testing. If I change the parent class to Mastering, crouching does not work, but the camera returns to normal. I have been working on this problem for over a week and I would be grateful if someone would give some suggestions as to what could be the reason :(
